github:
  description: "OpenOffice.org Website"
  homepage: "https://www.openoffice.org/"
  labels:
    - openoffice
    - website
    - jbake
  features:
    issues: true

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: commits@openoffice.apache.org
  issues: dev@openoffice.apache.org
  pullrequests: dev@openoffice.apache.org
