#ifndef __com_sun_star_scripting_XModules_idl__
#define __com_sun_star_scripting_XModules_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/scripting/XMethod.idl>

module com { module sun { module star { module scripting {

interface XModules: com::sun::star::uno::XInterface {
	/* from original i/f spec this should return a flat list of
	 * the available methods, and leave any hierarchical organisation
	 * of same to the UI */
	sequence <string> getAvailableMethods();
};
}; }; }; };
#endif
