#ifndef __com_sun_star_scripting_ScriptRegisterException_idl__
#define __com_sun_star_scripting_ScriptRegisterException_idl__

#ifndef __com_sun_star_uno_Exception_idl__
#include <com/sun/star/uno/Exception.idl>
#endif

module com {
  module sun {
    module star {
      module scripting {
      
        /** Indicates that there is a problem in registering the script engine
         */
        exception ScriptRegisterException: com::sun::star::uno::Exception
        {
          /** The Engine that tried to be (de)registered
          */
          string engine;
        };
      };
    };
  };
};
        
#endif
