#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/scripting/XMethod.idl>

module com { module sun { module star { module scripting {

// this service should be implemented once for each language with which
// we wish to script
service ScriptEngine {
	interface com::sun::star::scripting::XModules;
	interface com::sun::star::scripting::XBind;
	interface com::sun::star::scripting::XScriptEngine;

};
}; }; }; };
