#ifndef __com_sun_star_scripting_ScriptStartedEvent__ 
#define __com_sun_star_scripting_ScriptStartedEvent__
#ifndef __com_sun_star_lang_EventObject_idl__ 
#include <com/sun/star/lang/EventObject.idl> 
#endif 

module com { 
  module sun { 
    module star { 
      module scripting {

        struct ScriptStartedEvent: com::sun::star::lang::EventObject {
          string scriptName;
        };
      }; 
    }; 
  };
};
#endif

