#ifndef __com_sun_star_scripting_XMonitorListener__ 
#define __com_sun_star_scripting_XMonitorListener__
#ifndef __com_sun_star_uno_XInterface_idl__ 
#include <com/sun/star/uno/XInterface.idl> 
#endif 
#include <com/sun/star/lang/XEventListener.idl>
#include <ScriptCompletedEvent.idl>
#include <ScriptStartedEvent.idl>

module com { 
  module sun { 
    module star { 
      module scripting {
        interface XMonitorListener: com::sun::star::lang::XEventListener {

          /** Will be executed when script is started
            *
            */
          void scriptStarted([in] ScriptStartedEvent e);
 
          /** Will be executed when script finishes
            * 
            */
          void scriptCompleted([in] ScriptCompletedEvent e);
        };
      }; 
    }; 
  };
};
#endif

