/* first element: redir will redirect to contributing page, then to url,
   "here" will offer the download here and "skip" will directly go to the NL-webpage
   if NL-group has its own contributing webpage and want to use it */

/* skip for all, since contributing-page doesn't redirect anymore ...
   v1: ISO-short with array of 'skip/here' (old, not used),
   v2: language name in en-US,
   v3: link to NL-webpage,
   v4: flag indicating if builds with JRE are available,
   v5: flag for mirrorsystem usage ('y' to use Mirrorbrain and 'n' to use the NL-webpage),
   v6: flag for mirrorsystem for Mac OS (only in combination with previous flag !) */

/* v1		   , v2			      , v3					          ,v4, v5, v6 */

var languages = {
"ar": {"-": ['skip', 'Arabic',                'http://ar.openoffice.org/',                        'y','y','y']},
"eu": {"-": ['skip', 'Basque',                'http://eu.openoffice.org/',                        'y','y','y']},
"bn": {"-": ['skip', 'Bengali',               'http://bn.openoffice.org/',                        'y','y','y']},
"bg": {"-": ['skip', 'Bulgarian',             'http://bg.openoffice.org/',                        'y','y','y']},
"ca": {"-": ['skip', 'Catalan',               'http://www.softcatala.org/projectes/openoffice/',  'y','y','y'],
      "ca": ['skip', 'Catalan',               'http://www.softcatala.org/projectes/openoffice/',  'y','y','y'],
      "xv": ['skip', 'Catalan (Valencian)',   'http://download.openoffice.org/other.html',        'y','y','y']},
"cs": {"-": ['skip', 'Czech',                 'http://cs.openoffice.org/',                        'y','y','y']},
"zh": {"-": ['skip', 'Chinese',               'http://zh.openoffice.org/new/zh_cn/downloads.html','y','y','y'],
      "cn": ['skip', 'Chinese (simplified)',  'http://zh.openoffice.org/new/zh_cn/downloads.html','y','y','y'],
      "tw": ['skip', 'Chinese (traditional)', 'http://zh.openoffice.org/new/zh_tw/downloads.html','y','y','y']},
"da": {"-": ['skip', 'Danish',                'http://da.openoffice.org/',                        'y','y','y']},
"nl": {"-": ['skip', 'Dutch',                 'http://nl.openoffice.org/downloaden.html',         'y','y','y']},
"en": {"-": ['here', 'English',               'http://download.openoffice.org/other.html',        'y','y','y'],
      "en": ['here', 'English',               'http://download.openoffice.org/other.html',        'y','y','y'],
      "us": ['here', 'English (US)',          'http://download.openoffice.org/other.html',        'y','y','y'],
      "gb": ['here', 'English (British)',     'http://download.openoffice.org/other.html',        'y','y','y']},
"et": {"-": ['skip', 'Estonian',              'http://download.openoffice.org/other.html',        'y','y','y']},
"fi": {"-": ['skip', 'Finnish',               'http://fi.openoffice.org/lataa.html',              'y','y','y']},
"fr": {"-": ['skip', 'French',                'http://fr.openoffice.org/',                        'y','y','y']},
"gl": {"-": ['skip', 'Galician',              'http://gl.openoffice.org/',                        'y','y','y']},
"de": {"-": ['skip', 'German',                'http://de.openoffice.org/',                        'y','y','y']},
"el": {"-": ['skip', 'Greek',                 'http://el.openoffice.org/',                        'y','y','y']},
"he": {"-": ['skip', 'Hebrew',                'http://www.openoffice.org.il/',                    'y','y','y']},
"hu": {"-": ['skip', 'Hungarian',             'http://hu.openoffice.org/about-downloads.html',    'y','y','y']},
"ga": {"-": ['skip', 'Irish',                 'http://ga.openoffice.org/',                        'y','y','y']},
"it": {"-": ['skip', 'Italian',               'http://it.openoffice.org/download/',               'y','y','y']},
"ja": {"-": ['skip', 'Japanese',              'http://ja.openoffice.org/',                        'y','y','y']},
"km": {"-": ['skip', 'Khmer',                 'http://km.openoffice.org/',                        'y','y','y']},
"ko": {"-": ['skip', 'Korean',                'http://ko.openoffice.org/',                        'n','y','y']},
"lt": {"-": ['skip', 'Lithuanian',            'http://lt.openoffice.org/',                        'y','y','y']},
"mk": {"-": ['skip', 'Macedonian',            'http://mk.openoffice.org/',                        'y','y','y']},
"nb": {"-": ['skip', 'Norwegian (Bokmal)',    'http://no.openoffice.org/',                        'y','y','y']},
"om": {"-": ['skip', 'Oromo',                 'http://om.openoffice.org/',                        'y','y','y']},
"pl": {"-": ['skip', 'Polish',                'http://pl.openoffice.org/product.download.html',   'y','y','y']},
"pt": {"-": ['skip', 'Portuguese (European)', 'http://pt.openoffice.org/download/download.htm',   'y','y','y'],
      "pt": ['skip', 'Portuguese (European)', 'http://pt.openoffice.org/download/download.htm',   'y','y','y'],
      "br": ['skip', 'Portuguese (Brazilian)','http://br-pt.openoffice.org/',                     'y','y','y']},
"ru": {"-": ['skip', 'Russian',               'http://ru.openoffice.org/',                        'y','y','y']},
"sr": {"-": ['skip', 'Serbian (Cyrillic)',    'http://sr.openoffice.org/preuzmi.html',            'y','y','y']},
"sh": {"-": ['skip', 'Serbian (Latin)',       'http://sr.openoffice.org/lat/preuzmi.html',        'y','y','y']},
"sl": {"-": ['skip', 'Slovenian',             'http://sl.openoffice.org/',                        'y','y','y']},
"es": {"-": ['skip', 'Spanish',               'http://es.openoffice.org/programa/',               'y','y','y']},
"sv": {"-": ['skip', 'Swedish',               'http://sv.openoffice.org/get/',                    'y','y','y']},
"tr": {"-": ['skip', 'Turkish',               'http://tr.openoffice.org/',                        'y','y','y']},
"vi": {"-": ['skip', 'Vietnamese',            'http://vi.openoffice.org/',                        'y','y','y']},

"as": {"-": ['skip', 'Assamese',              'http://as.openoffice.org/',                        'n','n','n']},
"ast":{"-": ['skip', 'Asturian',              'http://ast.openoffice.org/',                       'n','n','n']},
"be": {"-": ['skip', 'Belarusian',            'http://be.openoffice.org/',                        'n','n','n'],
      "be": ['skip', 'Belarusian',            'http://be.openoffice.org/',                        'n','n','n'],
      "by": ['skip', 'Belarusian',            'http://be.openoffice.org/',                        'n','n','n']},
"my": {"-": ['skip', 'Burmese',               'http://my.openoffice.org/',                        'n','n','n']},
"hr": {"-": ['skip', 'Croatian',              'http://hr.openoffice.org/',                        'n','n','n']},
"dz": {"-": ['skip', 'Dzongkha',              'http://dz.openoffice.org/',                        'n','n','n']},
"eo": {"-": ['skip', 'Esperanto',             'http://eo.openoffice.org/',                        'n','n','n']},
"ka": {"-": ['skip', 'Georgian',              'http://ka.openoffice.org/',                        'n','n','n']},
"gu": {"-": ['skip', 'Gujarati',              'http://gu.openoffice.org/',                        'n','n','n']},
"hi": {"-": ['skip', 'Hindi',                 'http://hi.openoffice.org/',                        'n','n','n']},
"is": {"-": ['skip', 'Icelandic',             'http://is.openoffice.org/',                        'n','n','n']},
"id": {"-": ['skip', 'Indonesian',            'http://id.openoffice.org/',                        'n','n','n']},
"kn": {"-": ['skip', 'Kannada',               'http://kn.openoffice.org/',                        'n','n','n']},
"ku": {"-": ['skip', 'Kurdish',               'http://ku.openoffice.org/',                        'n','n','n']},
"lv": {"-": ['skip', 'Latvian',               'http://lv.openoffice.org/',                        'n','n','n']},
"lo": {"-": ['skip', 'Laotian',               'http://lo.openoffice.org/',                        'n','n','n']},
"ml": {"-": ['skip', 'Malayalam',             'http://ml.openoffice.org/',                        'n','n','n']},
"ms": {"-": ['skip', 'Malaysian',             'http://ms.openoffice.org/',                        'n','n','n']},
"mr": {"-": ['skip', 'Marathi',               'http://mr.openoffice.org/',                        'n','n','n']},
"mn": {"-": ['skip', 'Mongolian',             'http://mn.openoffice.org/',                        'n','n','n']},
"nn": {"-": ['skip', 'Norwegian (Nynorsk)',   'http://no.openoffice.org/',                        'n','n','n']},
"no": {"-": ['skip', 'Norwegian',             'http://no.openoffice.org/',                        'n','n','n']},
"oc": {"-": ['skip', 'Occitan',               'http://oc.openoffice.org/',                        'n','n','n']},
"or": {"-": ['skip', 'Oriya',                 'http://or.openoffice.org/',                        'n','n','n']},
"pa": {"-": ['skip', 'Punjabi',               'http://pa.openoffice.org/',                        'n','n','n'],
      "pa": ['skip', 'Punjabi',               'http://pa.openoffice.org/',                        'n','n','n'],
      "in": ['skip', 'Punjabi',               'http://pa.openoffice.org/',                        'n','n','n']},
"ro": {"-": ['skip', 'Romanian',              'http://ro.openoffice.org/',                        'n','n','n']},
"si": {"-": ['skip', 'Sinhala',               'http://si.openoffice.org/',                        'n','n','n']},
"sk": {"-": ['skip', 'Slovak',                'http://sk.openoffice.org/',                        'n','n','n']},
"ta": {"-": ['skip', 'Tamil',                 'http://ta.openoffice.org/',                        'n','n','n']},
"te": {"-": ['skip', 'Telugu',                'http://te.openoffice.org/',                        'n','n','n']},
"th": {"-": ['skip', 'Thai',                  'http://th.openoffice.org/',                        'n','n','n']},
"uk": {"-": ['skip', 'Ukrainian',             'http://uk.openoffice.org/',                        'n','n','n']},
"ug": {"-": ['skip', 'Uyghur',                'http://ug.openoffice.org/',                        'n','n','n']},
"uz": {"-": ['skip', 'Uzbek',                 'http://uz.openoffice.org/',                        'n','n','n']},
"cy": {"-": ['skip', 'Welsh',                 'http://cy.openoffice.org/',                        'n','n','n']}
};
