#ifndef __com_sun_star_scripting_storage_ScriptInfo_idl__
#define __com_sun_star_scripting_storage_ScriptInfo_idl__

#ifndef __com_sun_star_scripting_storage_XScriptInfo_idl__
#include <drafts/com/sun/star/scripting/storage/XScriptInfo.idl>
#endif

#ifndef __com_sun_star_scripting_storage_XScriptStore_idl__
#include <drafts/com/sun/star/scripting/storage/XScriptStore.idl>
#endif

//==============================================================================

module drafts { module com { module sun { module star { module scripting { module storage {

//==============================================================================
/** 
  This service provides access for script related information
*/
service ScriptInfo
{
/**
  This interface provides acces to one script's information
*/
  interface drafts::com::sun::star::scripting::storage::XScriptInfo;

  interface drafts::com::sun::star::scripting::storage::XScriptStore;

};

}; };  };  };  };  };
#endif
