#ifndef __com_sun_star_scripting_storage_XScriptImpl_idl__
#define __com_sun_star_scripting_storage_XScriptImpl_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

module com { module sun { module star { module scripting { module storage {
//==============================================================================
/** 
This interface provides detail to clients that require to resolve logical script
URI's to a specific language URI.
*/
interface XScriptImpl : XInterface
{

//------------------------------------------------------------------------------
/** 
@returns
  A sequence of language specific script URI's for the specified language.
*/
  sequence <string> getLanguageImpls([in] string langType);

//------------------------------------------------------------------------------
/**
@returns
  A sequence of script URI's for all languages implementing the script.
*/
  sequence <string> getImpls();
}

};  };  };  }; 
#endif
