#ifndef __com_sun_star_scripting_BindException_idl__
#define __com_sun_star_scripting_BindException_idl__

#ifndef __com_sun_star_uno_Exception_idl__
#include <com/sun/star/uno/Exception.idl>
#endif

module com {
  module sun {
    module star {
      module scripting {
      
        /** Indicates that there is a problem in binding the method
         */
        exception BindException: com::sun::star::uno::Exception
        {
          /** The method that tried to be bound
          */
          string Method;
        };
      };
    };
  };
};
        
#endif
