function countTags(n) {
	var numtags=0;
	if (n.nodeType == 1 /*Node.ELEMENT_NODE*/)
		numtags++;
	var children = n.childNodes;
	for (var i=0 ; i < children.length; i++) {
		numtags += countTags(children[i]);
	}
	return numtags;
}

// myform = form object
// myselect = select object name

function formHandler(myURL)
{

//alert("MyURL : " + myURL);
if (myURL == 'Italiano') return;
nag2myURL="contribute.html?continue="+escape(myURL);
window.location.href = nag2myURL;
//window.open(myURL);

}

function makeOSMirrors (s_index)
{

var myOS= new Array('windows','linux','ppclinux','solaris','solarisIntel','freebsd','mac');

//input hopefully
var whatOS=myOS[s_index-1];
//alert("s_index: " + s_index);
//alert("whatOS: " + whatOS);


OSinfo = new Object;

OSinfo.windows = new Array(2);
OSinfo.windows[0] = new Array();
OSinfo.windows[1] = new Array();
OSinfo.mac = new Array(2);
OSinfo.mac[0] = new Array();
OSinfo.mac[1] = new Array();
OSinfo.ppclinux = new Array(2);
OSinfo.ppclinux[0] = new Array();
OSinfo.ppclinux[1] = new Array();
OSinfo.freebsd = new Array(2);
OSinfo.freebsd[0] = new Array();
OSinfo.freebsd[1] = new Array();
OSinfo.linux = new Array(2);
OSinfo.linux[0] = new Array();
OSinfo.linux[1] = new Array();
OSinfo.solaris = new Array(2);
OSinfo.solaris[0] = new Array();
OSinfo.solaris[1] = new Array();
OSinfo.solarisIntel = new Array(2);
OSinfo.solarisIntel[0] = new Array();
OSinfo.solarisIntel[1] = new Array();
//wants to do column load
// aha--perl like array processing--this does row loads
//windows=[['0','1'],['2','3'],['4','5'],['6','7']];


OSinfo.windows=[
['Africa-Saix',
'ftp://ftp.saix.net/pub/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Australia-Pacific Internet',
'http://mirror.pacific.net.au/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Australia-Planet Mirror',
'http://planetmirror.com/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Austria-Vienna UT',
'http://gd.tuwien.ac.at/office/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Belgium-Belnet',
'http://ftp.belnet.be/pub/mirror/ftp.openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Belgium-Scarlet',
'http://ftp.scarlet.be/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Belgium-KULeuvenNet',
 'ftp://ftp.kulnet.kuleuven.ac.be/pub/mirror/openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Belgium-Skynet',
'ftp://ftp.openoffice.skynet.be/pub/ftp.openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Brazil-Linorg',
'http://linorg.usp.br/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Brazil-Pontifica U.Catòlica do Paranà',
'ftp://ftp.pucpr.br/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Bulgaria-SpectrumNet',
'http://ftp.spnet.net/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Canada-Cygnal',
'http://openoffice.mirror.rafal.ca/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Canada (Québec)-GULUS (Sherbrooke LUG)',
'http://gulus.USherbrooke.ca/pub/appl/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Czech Republic-CVUT',
'http://ftp.sh.cvut.cz/MIRRORS/OpenOffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Denmark-Sunsite',
'http://mirrors.sunsite.dk/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Finland-FUNET',
'ftp://ftp.funet.fi/pub/mirrors/openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['France-Proxad',
'ftp://ftp.proxad.net/mirrors/ftp.openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['France-CICT',
'ftp://openoffice.cict.fr/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Germany-Aachen',
'ftp://sunsite.informatik.rwth-aachen.de/pub/mirror/OpenOffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Germany-Chemitz',
'ftp://ftp.tu-chemnitz.de/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Germany-Esslingen',
'ftp://ftp-stud.fht-esslingen.de/pub/Mirrors/ftp.openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Germany-TU-BS',
'ftp://openoffice.tu-bs.de/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Germany-XaraNet',
'http://mirror.xaranet.de/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Greece-EllaK',
'http://www.ellak.gr/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Greece-NTUA',
'http://ftp.ntua.gr/pub/OpenOffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Hungary-HULK',
'http://ftp.linux.hr/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Hungary-FSF Hungary',
'http://ftp.fsf.hu/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Iceland-RHNet',
'http://ftp.rhnet.is/pub/OpenOffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Ireland-HEANet',
'http://ftp.heanet.ie/mirrors/openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Italy-GARR',
'http://na.mirror.garr.it/mirrors/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Indonesia-Gadjah Mada University',
'http://openoffice.ugm.ac.id/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Indonesia-Si Komo',
'http://komo.vlsm.org/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Indonesia-Si Kambing',
'http://kambing.vlsm.org/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Ireland-Irelands National Education and Research Network',
'http://ftp.heanet.ie/mirrors/openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Italy-Web-Spread.com',
'http://mirrors.web-spread.com/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Japan-KDDI',
'ftp://ftp.kddlabs.co.jp/office/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Japan-Ring',
'ftp://ftp.ring.gr.jp/pub/misc/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Japan-Yamagata U.',
'http://ftp.yz.yamagata-u.ac.jp/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Lithuania',
'http://files.akl.lt/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Netherlands-UUG',
'http://ftp.nluug.nl/pub/office/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Netherlands-SNT Server',
'http://vlaai.snt.utwente.nl/pub/software/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Netherlands-Ninja',
'http://niihau.student.utwente.nl/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Netherlands-Borft',
'http://borft.student.utwente.nl/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Poland-Poznan',
'ftp://ftp.man.poznan.pl/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Portugal-NEACM',
'http://neacm.fe.up.pt/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Portugal-UBI',
'http://ftpdem.ubi.pt/OpenOffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Romania-Evolva',
'ftp://mirrors.evolva.ro/openoffice.org/stable2.0.0/OOo_2.0.0rc3_051014_Win32Intel_install_it.exe'],
['Romania-Idlis',
'http://ftp.idilis.ro/mirrors/openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Romania-RoEduNet',
'http://ftp.iasi.roedu.net/mirrors/openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Russia-CHG',
'ftp://ftp.chg.ru/pub/OpenOffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Serbia and Montenegro-RC ETF server',
'http://mirror.etf.bg.ac.yu/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Singapore-Averse.net',
'http://mirror.averse.net/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Slovenia-Bevc',
'http://mirrors.bevc.net/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['South Africa-IS',
'ftp://ftp.is.co.za/mirrors/OpenOffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['South Africa-SAIX',
'ftp://ftp.saix.net/pub/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['South Korea-kr.freebsd',
'ftp://ftp.kr.freebsd.org/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Spain-Rediris',
'http://ftp.rediris.es/ftp/mirror/openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Sweden-Sunet',
'http://ftp.sunet.se/pub/Office/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Switzerland-SolNet',
'ftp://ftp.solnet.ch/mirror/OpenOffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Switzerland-SWITCHmirror',
'ftp://mirror.switch.ch/mirror/OpenOffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['UK-JISC',
'http://www.mirror.ac.uk/mirror/sunsite.dk/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'], 
['UK-UK Mirror Service',
'http://www.mirrorservice.org/sites/ny1.mirror.openoffice.org/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'], 
['USA-Collab.Net',
'http://openoffice.collab.net/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['USA-ISC',
'http://mirrors.isc.org/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['USA-TDS',
'ftp://openoffice.mirrors.tds.net/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['USA-Indiana U',
'ftp://ftp.ussg.iu.edu/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['USA-pair',
'http://openoffice.mirrors.pair.com/ftp/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['USA-Secs Up',
'ftp://openofficeorg.secsup.org/pub/software/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['USA-ibiblio.org',
'http://mirrors.ibiblio.org/pub/mirrors/openoffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe'],
['Taiwan-NCTU',
'ftp://ftp.nctu.edu.tw/UNIX/OpenOffice/localized/it/2.0.1/OOo_2.0.1_Win32Intel_install_it.exe']
];
//end windows mirrors

OSinfo.linux=[
['Africa-Saix',
'ftp://ftp.saix.net/pub/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Australia-Pacific Internet',
'http://mirror.pacific.net.au/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Australia-Planet Mirror',
'http://planetmirror.com/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Austria-Vienna UT',
'http://gd.tuwien.ac.at/office/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Belgium-Belnet',
'http://ftp.belnet.be/pub/mirror/ftp.openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Belgium-Scarlet',
'http://ftp.scarlet.be/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Belgium-KULeuvenNet',
 'ftp://ftp.kulnet.kuleuven.ac.be/pub/mirror/openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Belgium-Skynet',
'ftp://ftp.openoffice.skynet.be/pub/ftp.openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Brazil-Linorg',
'http://linorg.usp.br/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Brazil-Pontifica U.Catòlica do Paranà',
'ftp://ftp.pucpr.br/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Bulgaria-SpectrumNet',
'http://ftp.spnet.net/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Canada-Cygnal',
'http://openoffice.mirror.rafal.ca/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Canada (Québec)-GULUS (Sherbrooke LUG)',
'http://gulus.USherbrooke.ca/pub/appl/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Czech Republic-CVUT',
'http://ftp.sh.cvut.cz/MIRRORS/OpenOffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Denmark-Sunsite',
'http://mirrors.sunsite.dk/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Finland-FUNET',
'ftp://ftp.funet.fi/pub/mirrors/openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['France-Proxad',
'ftp://ftp.proxad.net/mirrors/ftp.openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['France-CICT',
'ftp://openoffice.cict.fr/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Germany-Aachen',
'ftp://sunsite.informatik.rwth-aachen.de/pub/mirror/OpenOffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Germany-Chemitz',
'ftp://ftp.tu-chemnitz.de/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Germany-Esslingen',
'ftp://ftp-stud.fht-esslingen.de/pub/Mirrors/ftp.openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Germany-TU-BS',
'ftp://openoffice.tu-bs.de/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Germany-XaraNet',
'http://mirror.xaranet.de/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Greece-EllaK',
'http://www.ellak.gr/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Greece-NTUA',
'http://ftp.ntua.gr/pub/OpenOffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Hungary-HULK',
'http://ftp.linux.hr/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Hungary-FSF Hungary',
'http://ftp.fsf.hu/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Iceland-RHNet',
'http://ftp.rhnet.is/pub/OpenOffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Ireland-HEANet',
'http://ftp.heanet.ie/mirrors/openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Italy-GARR',
'http://na.mirror.garr.it/mirrors/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Indonesia-Gadjah Mada University',
'http://openoffice.ugm.ac.id/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Indonesia-Si Komo',
'http://komo.vlsm.org/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Indonesia-Si Kambing',
'http://kambing.vlsm.org/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Ireland-Irelands National Education and Research Network',
'http://ftp.heanet.ie/mirrors/openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Italy-Web-Spread.com',
'http://mirrors.web-spread.com/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Japan-KDDI',
'ftp://ftp.kddlabs.co.jp/office/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Japan-Ring',
'ftp://ftp.ring.gr.jp/pub/misc/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Japan-Yamagata U.',
'http://ftp.yz.yamagata-u.ac.jp/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Lithuania',
'http://files.akl.lt/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Netherlands-UUG',
'http://ftp.nluug.nl/pub/office/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Netherlands-SNT Server',
'http://vlaai.snt.utwente.nl/pub/software/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Netherlands-Ninja',
'http://niihau.student.utwente.nl/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Netherlands-Borft',
'http://borft.student.utwente.nl/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Poland-Poznan',
'ftp://ftp.man.poznan.pl/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Portugal-NEACM',
'http://neacm.fe.up.pt/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Portugal-UBI',
'http://ftpdem.ubi.pt/OpenOffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Romania-Evolva',
'ftp://mirrors.evolva.ro/openoffice.org/stable2.0.0/OOo_2.0.0rc3_051015_LinuxIntel_install_it.tar.gz'],
['Romania-Idlis',
'http://ftp.idilis.ro/mirrors/openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Romania-RoEduNet',
'http://ftp.iasi.roedu.net/mirrors/openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Russia-CHG',
'ftp://ftp.chg.ru/pub/OpenOffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Serbia and Montenegro-RC ETF server',
'http://mirror.etf.bg.ac.yu/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Singapore-Averse.net',
'http://mirror.averse.net/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Slovenia-Bevc',
'http://mirrors.bevc.net/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['South Africa-IS',
'ftp://ftp.is.co.za/mirrors/OpenOffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['South Africa-SAIX',
'ftp://ftp.saix.net/pub/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['South Korea-kr.freebsd',
'ftp://ftp.kr.freebsd.org/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Spain-Rediris',
'http://ftp.rediris.es/ftp/mirror/openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Sweden-Sunet',
'http://ftp.sunet.se/pub/Office/OpenOffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Switzerland-SolNet',
'ftp://ftp.solnet.ch/mirror/OpenOffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Switzerland-SWITCHmirror',
'ftp://mirror.switch.ch/mirror/OpenOffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['UK-JISC',
'http://www.mirror.ac.uk/mirror/sunsite.dk/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'], 
['UK-UK Mirror Service',
'http://www.mirrorservice.org/sites/ny1.mirror.openoffice.org/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'], 
['USA-Collab.Net',
'http://openoffice.collab.net/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['USA-ISC',
'http://mirrors.isc.org/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['USA-TDS',
'ftp://openoffice.mirrors.tds.net/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['USA-Indiana U',
'ftp://ftp.ussg.iu.edu/pub/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['USA-pair',
'http://openoffice.mirrors.pair.com/ftp/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['USA-Secs Up',
'ftp://openofficeorg.secsup.org/pub/software/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['USA-ibiblio.org',
'http://mirrors.ibiblio.org/pub/mirrors/openoffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz'],
['Taiwan-NCTU',
'ftp://ftp.nctu.edu.tw/UNIX/OpenOffice/localized/it/2.0.1/OOo_2.0.1_LinuxIntel_install_it.tar.gz']
];
//end linux mirrors



OSinfo.ppclinux=[
['PPC Linux page',
'http://www.openoffice.org/project/porting/linuxppc/ppclinks.html']
];
//end ppc linux 

OSinfo.freebsd=[
['FreeBSD page',
'http://www.openoffice.org/project/porting/freebsd/']
];
//end freebsd

OSinfo.mac =[
['Italy-GARR',
'http://na.mirror.garr.it/mirrors/openoffice/localized/it/2.0.1/OOo_2.0.1_MacOSX_install_it.dmg'],
['Mac OS X page',
'http://www.openoffice.org/project/porting/mac/ooo-osx_downloads.html']
];
//end Mac




OSinfo.solaris=[
['Africa-Saix',
'ftp://ftp.saix.net/pub/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Australia-Pacific Internet',
'http://mirror.pacific.net.au/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Australia-Planet Mirror',
'http://planetmirror.com/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Austria-Vienna UT',
'http://gd.tuwien.ac.at/office/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Belgium-Belnet',
'http://ftp.belnet.be/pub/mirror/ftp.openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Belgium-Scarlet',
'http://ftp.scarlet.be/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Belgium-KULeuvenNet',
 'ftp://ftp.kulnet.kuleuven.ac.be/pub/mirror/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Belgium-Skynet',
'ftp://ftp.openoffice.skynet.be/pub/ftp.openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Brazil-Linorg',
'http://linorg.usp.br/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Brazil-Pontifica U.Catòlica do Paranà',
'ftp://ftp.pucpr.br/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Bulgaria-SpectrumNet',
'http://ftp.spnet.net/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Canada-Cygnal',
'http://openoffice.mirror.rafal.ca/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Canada (Québec)-GULUS (Sherbrooke LUG)',
'http://gulus.USherbrooke.ca/pub/appl/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Czech Republic-CVUT',
'http://ftp.sh.cvut.cz/MIRRORS/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Denmark-Sunsite',
'http://mirrors.sunsite.dk/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Finland-FUNET',
'ftp://ftp.funet.fi/pub/mirrors/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['France-Proxad',
'ftp://ftp.proxad.net/mirrors/ftp.openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['France-CICT',
'ftp://openoffice.cict.fr/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Germany-Aachen',
'ftp://sunsite.informatik.rwth-aachen.de/pub/mirror/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Germany-Chemitz',
'ftp://ftp.tu-chemnitz.de/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Germany-Esslingen',
'ftp://ftp-stud.fht-esslingen.de/pub/Mirrors/ftp.openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Germany-TU-BS',
'ftp://openoffice.tu-bs.de/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Germany-XaraNet',
'http://mirror.xaranet.de/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Greece-EllaK',
'http://www.ellak.gr/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Greece-NTUA',
'http://ftp.ntua.gr/pub/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Hungary-FSF Hungary',
'http://ftp.fsf.hu/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Iceland-RHNet',
'http://ftp.rhnet.is/pub/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Ireland-HEANet',
'http://ftp.heanet.ie/mirrors/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Italy-GARR',
'http://na.mirror.garr.it/mirrors/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Indonesia-Gadjah Mada University',
'http://openoffice.ugm.ac.id/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Indonesia-Si Komo',
'http://komo.vlsm.org/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Indonesia-Si Kambing',
'http://kambing.vlsm.org/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Ireland-Irelands National Education and Research Network',
'http://ftp.heanet.ie/mirrors/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Italy-Web-Spread.com',
'http://mirrors.web-spread.com/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Japan-KDDI',
'ftp://ftp.kddlabs.co.jp/office/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Japan-Ring',
'ftp://ftp.ring.gr.jp/pub/misc/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Japan-Yamagata U.',
'http://ftp.yz.yamagata-u.ac.jp/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Lithuania',
'http://files.akl.lt/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Netherlands-UUG',
'http://ftp.nluug.nl/pub/office/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Netherlands-SNT Server',
'http://vlaai.snt.utwente.nl/pub/software/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Netherlands-Ninja',
'http://niihau.student.utwente.nl/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Netherlands-Borft',
'http://borft.student.utwente.nl/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Poland-Poznan',
'ftp://ftp.man.poznan.pl/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Portugal-NEACM',
'http://neacm.fe.up.pt/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Portugal-UBI',
'http://ftpdem.ubi.pt/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Romania-Evolva',
'ftp://mirrors.evolva.ro/openoffice.org/stable2.0.0/OOo_2.0.0rc3_051014_SolarisSparc_install_it.tar.gz'],
['Romania-Idlis',
'http://ftp.idilis.ro/mirrors/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Romania-RoEduNet',
'http://ftp.iasi.roedu.net/mirrors/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Russia-CHG',
'ftp://ftp.chg.ru/pub/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Serbia and Montenegro-RC ETF server',
'http://mirror.etf.bg.ac.yu/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Singapore-Averse.net',
'http://mirror.averse.net/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Slovenia-Bevc',
'http://mirrors.bevc.net/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['South Africa-IS',
'ftp://ftp.is.co.za/mirrors/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['South Africa-SAIX',
'ftp://ftp.saix.net/pub/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['South Korea-kr.freebsd',
'ftp://ftp.kr.freebsd.org/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Spain-Rediris',
'http://ftp.rediris.es/ftp/mirror/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Sweden-Sunet',
'http://ftp.sunet.se/pub/Office/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Switzerland-SolNet',
'ftp://ftp.solnet.ch/mirror/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Switzerland-SWITCHmirror',
'ftp://mirror.switch.ch/mirror/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['UK-JISC',
'http://www.mirror.ac.uk/mirror/sunsite.dk/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'], 
['UK-UK Mirror Service',
'http://www.mirrorservice.org/sites/ny1.mirror.openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'], 
['USA-Collab.Net',
'http://openoffice.collab.net/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['USA-ISC',
'http://mirrors.isc.org/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['USA-TDS',
'ftp://openoffice.mirrors.tds.net/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['USA-Indiana U',
'ftp://ftp.ussg.iu.edu/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['USA-pair',
'http://openoffice.mirrors.pair.com/ftp/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['USA-Secs Up',
'ftp://openofficeorg.secsup.org/pub/software/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['USA-ibiblio.org',
'http://mirrors.ibiblio.org/pub/mirrors/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz'],
['Taiwan-NCTU',
'ftp://ftp.nctu.edu.tw/UNIX/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_SolarisSparc_install_it.tar.gz']
];
//end SolarisSparc mirrors



OSinfo.solarisIntel =[
['Africa-Saix',
'ftp://ftp.saix.net/pub/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Australia-Pacific Internet',
'http://mirror.pacific.net.au/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Australia-Planet Mirror',
'http://planetmirror.com/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Austria-Vienna UT',
'http://gd.tuwien.ac.at/office/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Belgium-Belnet',
'http://ftp.belnet.be/pub/mirror/ftp.openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Belgium-Scarlet',
'http://ftp.scarlet.be/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Belgium-KULeuvenNet',
 'ftp://ftp.kulnet.kuleuven.ac.be/pub/mirror/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Belgium-Skynet',
'ftp://ftp.openoffice.skynet.be/pub/ftp.openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Brazil-Linorg',
'http://linorg.usp.br/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Brazil-Pontifica U.Catòlica do Paranà',
'ftp://ftp.pucpr.br/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Bulgaria-SpectrumNet',
'http://ftp.spnet.net/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Canada-Cygnal',
'http://openoffice.mirror.rafal.ca/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Canada (Québec)-GULUS (Sherbrooke LUG)',
'http://gulus.USherbrooke.ca/pub/appl/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Czech Republic-CVUT',
'http://ftp.sh.cvut.cz/MIRRORS/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Denmark-Sunsite',
'http://mirrors.sunsite.dk/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Finland-FUNET',
'ftp://ftp.funet.fi/pub/mirrors/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['France-Proxad',
'ftp://ftp.proxad.net/mirrors/ftp.openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['France-CICT',
'ftp://openoffice.cict.fr/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Germany-Aachen',
'ftp://sunsite.informatik.rwth-aachen.de/pub/mirror/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Germany-Chemitz',
'ftp://ftp.tu-chemnitz.de/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Germany-Esslingen',
'ftp://ftp-stud.fht-esslingen.de/pub/Mirrors/ftp.openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Germany-TU-BS',
'ftp://openoffice.tu-bs.de/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Germany-XaraNet',
'http://mirror.xaranet.de/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Greece-EllaK',
'http://www.ellak.gr/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Greece-NTUA',
'http://ftp.ntua.gr/pub/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Hungary-HULK',
'http://ftp.linux.hr/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Hungary-FSF Hungary',
'http://ftp.fsf.hu/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Iceland-RHNet',
'http://ftp.rhnet.is/pub/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Ireland-HEANet',
'http://ftp.heanet.ie/mirrors/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Italy-GARR',
'http://na.mirror.garr.it/mirrors/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Indonesia-Gadjah Mada University',
'http://openoffice.ugm.ac.id/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Indonesia-Si Komo',
'http://komo.vlsm.org/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Indonesia-Si Kambing',
'http://kambing.vlsm.org/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Ireland-Irelands National Education and Research Network',
'http://ftp.heanet.ie/mirrors/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Italy-Web-Spread.com',
'http://mirrors.web-spread.com/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Japan-KDDI',
'ftp://ftp.kddlabs.co.jp/office/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Japan-Ring',
'ftp://ftp.ring.gr.jp/pub/misc/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Japan-Yamagata U.',
'http://ftp.yz.yamagata-u.ac.jp/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Lithuania',
'http://files.akl.lt/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Netherlands-UUG',
'http://ftp.nluug.nl/pub/office/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Netherlands-SNT Server',
'http://vlaai.snt.utwente.nl/pub/software/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Netherlands-Ninja',
'http://niihau.student.utwente.nl/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Netherlands-Borft',
'http://borft.student.utwente.nl/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Poland-Poznan',
'ftp://ftp.man.poznan.pl/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Portugal-NEACM',
'http://neacm.fe.up.pt/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Portugal-UBI',
'http://ftpdem.ubi.pt/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Romania-Evolva',
'ftp://mirrors.evolva.ro/openoffice.org/stable2.0.0/OOo_2.0.0rc3_051014_Solarisx86_install_it.tar.gz'],
['Romania-Idlis',
'http://ftp.idilis.ro/mirrors/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Romania-RoEduNet',
'http://ftp.iasi.roedu.net/mirrors/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Russia-CHG',
'ftp://ftp.chg.ru/pub/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Serbia and Montenegro-RC ETF server',
'http://mirror.etf.bg.ac.yu/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Singapore-Averse.net',
'http://mirror.averse.net/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Slovenia-Bevc',
'http://mirrors.bevc.net/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['South Africa-IS',
'ftp://ftp.is.co.za/mirrors/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['South Africa-SAIX',
'ftp://ftp.saix.net/pub/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['South Korea-kr.freebsd',
'ftp://ftp.kr.freebsd.org/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Spain-Rediris',
'http://ftp.rediris.es/ftp/mirror/openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Sweden-Sunet',
'http://ftp.sunet.se/pub/Office/OpenOffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Switzerland-SolNet',
'ftp://ftp.solnet.ch/mirror/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Switzerland-SWITCHmirror',
'ftp://mirror.switch.ch/mirror/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['UK-JISC',
'http://www.mirror.ac.uk/mirror/sunsite.dk/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'], 
['UK-UK Mirror Service',
'http://www.mirrorservice.org/sites/ny1.mirror.openoffice.org/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'], 
['USA-Collab.Net',
'http://openoffice.collab.net/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['USA-ISC',
'http://mirrors.isc.org/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['USA-TDS',
'ftp://openoffice.mirrors.tds.net/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['USA-Indiana U',
'ftp://ftp.ussg.iu.edu/pub/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['USA-pair',
'http://openoffice.mirrors.pair.com/ftp/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['USA-Secs Up',
'ftp://openofficeorg.secsup.org/pub/software/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['USA-ibiblio.org',
'http://mirrors.ibiblio.org/pub/mirrors/openoffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz'],
['Taiwan-NCTU',
'ftp://ftp.nctu.edu.tw/UNIX/OpenOffice/contrib/rc/2.0.1rc5/OOo_2.0.1rc5_051215_Solarisx86_install_it.tar.gz']
]
//end SolarisIntel

//length of current options
var opt_counter=1;
//alert("Array length for whatOS: " + OSinfo[whatOS].length);
// reset options
document.download.mirror.options.length=1;

OSinfo[whatOS].sort();
for (var i=0; i < OSinfo[whatOS].length ; i++) {
		var new_item=new Option(OSinfo[whatOS][i][0],OSinfo[whatOS][i][1]);
		document.download.mirror.options[opt_counter] = new_item;
//    alert(opt_counter + "new value :" + document.download.mirror.options[opt_counter].value);
		opt_counter++;
	}

}
// end mirror gen options function
// $Revision: 1.3 $ $Date: 2006/11/28 00:17:44 $

