</td>
<td width="1%" valign="top">&nbsp;</td>
<td width="15%" valign="top">
<table width="100%" border="1" bordercolor="#000000" cellspacing="0" cellpadding="5">
<tr><td class="it_nav">Introduzione</td></tr>
<tr><td>
<a href="../../index.html">Home Page</a><br>
<a href="../../varie/lang_it.html">Informazioni di base</a><br>
<a href="../../avvenimenti/avvenimenti.html">Avvenimenti</a>
</td></tr>
<tr><td class="it_nav">Contatto</td></tr>
<tr><td>
<a href="../../marketing/index.html">Informazioni</a><br>
<a href="../../varie/mailinglist.html">Mailing List</a><br>
<a href="../../varie/irc.html">Canale IRC</a><br>
<a href="../../marketing/comp_promo.html">Materiale Promozionale</a>
</td></tr>
<tr><td class="it_nav">Software</td></tr>
<tr><td>
<a href="../../varie/downloads.html">Download</a><br>
<a href="../../marketing/consulenti.html">CD-ROM e Supporto</a><br>
<a href="../../contribuire/spellcheck.html">Correttore Ortografico</a>
</td></tr>
<tr><td class="it_nav">Documentazione</td></tr>
<tr><td>
<a href="../../faq/utenti/index.html">FAQ</a><br>
<a href="index.html">Primi Passi...</a>
</td></tr>
<tr><td class="it_nav">Collaborare</td></tr>
<tr><td> 
<a href="../../contribuire/index.html">Ma come?</a><br>
<a href="../../contribuire/whiteboard.html">Whiteboard</a><br>
<a href="../../contribuire/progetti.html">Progetti</a><br>
<a href="../../contribuire/issuezilla.html">Segnalazione Bugs</a><br>
<a href="../../contribuire/codice.html">Contribuire al Codice</a>
</td></tr>
<tr><td class="it_nav">Varie</td></tr>
<tr><td>
<a href="../../marketing/logo_link.html">Logo per Links</a><br>
<a href="../../contribuire/legale.html">Legalese</a><br>
<a href="../../marketing/storia.html">Storia</a>
</td></tr>
</table></td></tr></table>
